/*
Copyright The Grove Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apicorev1alpha1 "github.com/ai-dynamo/grove/operator/api/core/v1alpha1"
	versioned "github.com/ai-dynamo/grove/operator/client/clientset/versioned"
	internalinterfaces "github.com/ai-dynamo/grove/operator/client/informers/externalversions/internalinterfaces"
	corev1alpha1 "github.com/ai-dynamo/grove/operator/client/listers/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterTopologyBindingInformer provides access to a shared informer and lister for
// ClusterTopologyBindings. Prefer using the type-safe variant (see [TypedClusterTopologyBindingInformer]).
type ClusterTopologyBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() corev1alpha1.ClusterTopologyBindingLister
}

// TypedClusterTopologyBindingInformer provides access to a shared informer and lister for
// ClusterTopologyBindings, including the type-safe TypedInformer variant.
// It is a superset of ClusterTopologyBindingInformer.
type TypedClusterTopologyBindingInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() ClusterTopologyBindingIndexInformer
	Lister() corev1alpha1.ClusterTopologyBindingLister
}

// ClusterTopologyBindingIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type ClusterTopologyBindingIndexInformer cache.TypedSharedIndexInformer[*apicorev1alpha1.ClusterTopologyBinding]

// ClusterTopologyBindingHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for ClusterTopologyBinding.
type ClusterTopologyBindingHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apicorev1alpha1.ClusterTopologyBinding]

// ClusterTopologyBindingDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for ClusterTopologyBinding.
type ClusterTopologyBindingDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apicorev1alpha1.ClusterTopologyBinding]

// ClusterTopologyBindingFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for ClusterTopologyBinding.
type ClusterTopologyBindingFilteringHandler = cache.TypedFilteringResourceEventHandler[*apicorev1alpha1.ClusterTopologyBinding]

// ClusterTopologyBindingIndexers is a specialization of [cache.TypedIndexers] for ClusterTopologyBinding.
type ClusterTopologyBindingIndexers = cache.TypedIndexers[*apicorev1alpha1.ClusterTopologyBinding]

// DeletedClusterTopologyBinding is a specialization of [cache.DeletedObject] for ClusterTopologyBinding.
type DeletedClusterTopologyBinding = cache.DeletedObject[*apicorev1alpha1.ClusterTopologyBinding]

type clusterTopologyBindingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterTopologyBindingInformer constructs a new informer for ClusterTopologyBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedClusterTopologyBindingInformer]).
func NewClusterTopologyBindingInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewClusterTopologyBindingInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedClusterTopologyBindingInformer constructs a new informer for ClusterTopologyBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedClusterTopologyBindingInformer(client versioned.Interface, resyncPeriod time.Duration, indexers ClusterTopologyBindingIndexers) ClusterTopologyBindingIndexInformer {
	return NewTypedClusterTopologyBindingInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredClusterTopologyBindingInformer constructs a new informer for ClusterTopologyBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredClusterTopologyBindingInformer]).
func NewFilteredClusterTopologyBindingInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedClusterTopologyBindingInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredClusterTopologyBindingInformer constructs a new informer for ClusterTopologyBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredClusterTopologyBindingInformer(client versioned.Interface, resyncPeriod time.Duration, indexers ClusterTopologyBindingIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) ClusterTopologyBindingIndexInformer {
	return NewTypedClusterTopologyBindingInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewClusterTopologyBindingInformerWithOptions constructs a new informer for ClusterTopologyBinding type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedClusterTopologyBindingInformerWithOptions]).
func NewClusterTopologyBindingInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedClusterTopologyBindingInformerWithOptions(client, options)
}

// NewTypedClusterTopologyBindingInformerWithOptions constructs a new informer for ClusterTopologyBinding type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedClusterTopologyBindingInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) ClusterTopologyBindingIndexInformer {
	gvr := schema.GroupVersionResource{Group: "grove.io", Version: "v1alpha1", Resource: "clustertopologybindings"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.ClusterTopologyBinding](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.GroveV1alpha1().ClusterTopologyBindings().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.GroveV1alpha1().ClusterTopologyBindings().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.GroveV1alpha1().ClusterTopologyBindings().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.GroveV1alpha1().ClusterTopologyBindings().Watch(ctx, opts)
			},
		}, client),
		&apicorev1alpha1.ClusterTopologyBinding{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *clusterTopologyBindingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedClusterTopologyBindingInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *clusterTopologyBindingInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *clusterTopologyBindingInformer) TypedInformer() ClusterTopologyBindingIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.ClusterTopologyBinding](f.factory.InformerFor(&apicorev1alpha1.ClusterTopologyBinding{}, f.defaultInformer))
}

func (f *clusterTopologyBindingInformer) Lister() corev1alpha1.ClusterTopologyBindingLister {
	return corev1alpha1.NewClusterTopologyBindingLister(f.Informer().GetIndexer())
}

// ToTypedClusterTopologyBindingInformer converts an untyped informer into a TypedClusterTopologyBindingInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *ClusterTopologyBinding. If that is not the case, calling type-safe methods of the returned
// TypedClusterTopologyBindingInformer leads to runtime panics. A safer alternative is to pass
// around a TypedClusterTopologyBindingInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedClusterTopologyBindingInformer(informer ClusterTopologyBindingInformer) TypedClusterTopologyBindingInformer {
	if informer, ok := informer.(TypedClusterTopologyBindingInformer); ok {
		return informer
	}
	return &clusterTopologyBindingTypedInformerAdapter{informer}
}

type clusterTopologyBindingTypedInformerAdapter struct {
	ClusterTopologyBindingInformer
}

func (a *clusterTopologyBindingTypedInformerAdapter) TypedInformer() ClusterTopologyBindingIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.ClusterTopologyBinding](a.Informer())
}

// ToClusterTopologyBindingIndexInformer converts an untyped informer into a ClusterTopologyBindingIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *ClusterTopologyBinding. If that is not the case, calling type-safe methods of the returned
// ClusterTopologyBindingIndexInformer leads to runtime panics. A safer alternative is to pass
// around a ClusterTopologyBindingIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToClusterTopologyBindingIndexInformer(informer cache.SharedIndexInformer) ClusterTopologyBindingIndexInformer {
	if informer, ok := informer.(ClusterTopologyBindingIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.ClusterTopologyBinding](informer)
}
