/*
Copyright The Grove Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apicorev1alpha1 "github.com/ai-dynamo/grove/operator/api/core/v1alpha1"
	versioned "github.com/ai-dynamo/grove/operator/client/clientset/versioned"
	internalinterfaces "github.com/ai-dynamo/grove/operator/client/informers/externalversions/internalinterfaces"
	corev1alpha1 "github.com/ai-dynamo/grove/operator/client/listers/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodCliqueSetInformer provides access to a shared informer and lister for
// PodCliqueSets. Prefer using the type-safe variant (see [TypedPodCliqueSetInformer]).
type PodCliqueSetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() corev1alpha1.PodCliqueSetLister
}

// TypedPodCliqueSetInformer provides access to a shared informer and lister for
// PodCliqueSets, including the type-safe TypedInformer variant.
// It is a superset of PodCliqueSetInformer.
type TypedPodCliqueSetInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() PodCliqueSetIndexInformer
	Lister() corev1alpha1.PodCliqueSetLister
}

// PodCliqueSetIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type PodCliqueSetIndexInformer cache.TypedSharedIndexInformer[*apicorev1alpha1.PodCliqueSet]

// PodCliqueSetHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for PodCliqueSet.
type PodCliqueSetHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apicorev1alpha1.PodCliqueSet]

// PodCliqueSetDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for PodCliqueSet.
type PodCliqueSetDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apicorev1alpha1.PodCliqueSet]

// PodCliqueSetFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for PodCliqueSet.
type PodCliqueSetFilteringHandler = cache.TypedFilteringResourceEventHandler[*apicorev1alpha1.PodCliqueSet]

// PodCliqueSetIndexers is a specialization of [cache.TypedIndexers] for PodCliqueSet.
type PodCliqueSetIndexers = cache.TypedIndexers[*apicorev1alpha1.PodCliqueSet]

// DeletedPodCliqueSet is a specialization of [cache.DeletedObject] for PodCliqueSet.
type DeletedPodCliqueSet = cache.DeletedObject[*apicorev1alpha1.PodCliqueSet]

type podCliqueSetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodCliqueSetInformer constructs a new informer for PodCliqueSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedPodCliqueSetInformer]).
func NewPodCliqueSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewPodCliqueSetInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedPodCliqueSetInformer constructs a new informer for PodCliqueSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedPodCliqueSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers PodCliqueSetIndexers) PodCliqueSetIndexInformer {
	return NewTypedPodCliqueSetInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredPodCliqueSetInformer constructs a new informer for PodCliqueSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredPodCliqueSetInformer]).
func NewFilteredPodCliqueSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedPodCliqueSetInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredPodCliqueSetInformer constructs a new informer for PodCliqueSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredPodCliqueSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers PodCliqueSetIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) PodCliqueSetIndexInformer {
	return NewTypedPodCliqueSetInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewPodCliqueSetInformerWithOptions constructs a new informer for PodCliqueSet type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedPodCliqueSetInformerWithOptions]).
func NewPodCliqueSetInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedPodCliqueSetInformerWithOptions(client, namespace, options)
}

// NewTypedPodCliqueSetInformerWithOptions constructs a new informer for PodCliqueSet type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedPodCliqueSetInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) PodCliqueSetIndexInformer {
	gvr := schema.GroupVersionResource{Group: "grove.io", Version: "v1alpha1", Resource: "podcliquesets"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.PodCliqueSet](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.GroveV1alpha1().PodCliqueSets(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.GroveV1alpha1().PodCliqueSets(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.GroveV1alpha1().PodCliqueSets(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.GroveV1alpha1().PodCliqueSets(namespace).Watch(ctx, opts)
			},
		}, client),
		&apicorev1alpha1.PodCliqueSet{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *podCliqueSetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedPodCliqueSetInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *podCliqueSetInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *podCliqueSetInformer) TypedInformer() PodCliqueSetIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.PodCliqueSet](f.factory.InformerFor(&apicorev1alpha1.PodCliqueSet{}, f.defaultInformer))
}

func (f *podCliqueSetInformer) Lister() corev1alpha1.PodCliqueSetLister {
	return corev1alpha1.NewPodCliqueSetLister(f.Informer().GetIndexer())
}

// ToTypedPodCliqueSetInformer converts an untyped informer into a TypedPodCliqueSetInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *PodCliqueSet. If that is not the case, calling type-safe methods of the returned
// TypedPodCliqueSetInformer leads to runtime panics. A safer alternative is to pass
// around a TypedPodCliqueSetInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedPodCliqueSetInformer(informer PodCliqueSetInformer) TypedPodCliqueSetInformer {
	if informer, ok := informer.(TypedPodCliqueSetInformer); ok {
		return informer
	}
	return &podCliqueSetTypedInformerAdapter{informer}
}

type podCliqueSetTypedInformerAdapter struct {
	PodCliqueSetInformer
}

func (a *podCliqueSetTypedInformerAdapter) TypedInformer() PodCliqueSetIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.PodCliqueSet](a.Informer())
}

// ToPodCliqueSetIndexInformer converts an untyped informer into a PodCliqueSetIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *PodCliqueSet. If that is not the case, calling type-safe methods of the returned
// PodCliqueSetIndexInformer leads to runtime panics. A safer alternative is to pass
// around a PodCliqueSetIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToPodCliqueSetIndexInformer(informer cache.SharedIndexInformer) PodCliqueSetIndexInformer {
	if informer, ok := informer.(PodCliqueSetIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apicorev1alpha1.PodCliqueSet](informer)
}
