//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Grove Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v2 "k8s.io/api/autoscaling/v2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalingConfig) DeepCopyInto(out *AutoScalingConfig) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]v2.MetricSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalingConfig.
func (in *AutoScalingConfig) DeepCopy() *AutoScalingConfig {
	if in == nil {
		return nil
	}
	out := new(AutoScalingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTopologyBinding) DeepCopyInto(out *ClusterTopologyBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTopologyBinding.
func (in *ClusterTopologyBinding) DeepCopy() *ClusterTopologyBinding {
	if in == nil {
		return nil
	}
	out := new(ClusterTopologyBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTopologyBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTopologyBindingList) DeepCopyInto(out *ClusterTopologyBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterTopologyBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTopologyBindingList.
func (in *ClusterTopologyBindingList) DeepCopy() *ClusterTopologyBindingList {
	if in == nil {
		return nil
	}
	out := new(ClusterTopologyBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTopologyBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTopologyBindingSpec) DeepCopyInto(out *ClusterTopologyBindingSpec) {
	*out = *in
	if in.Levels != nil {
		in, out := &in.Levels, &out.Levels
		*out = make([]TopologyLevel, len(*in))
		copy(*out, *in)
	}
	if in.SchedulerTopologyBindings != nil {
		in, out := &in.SchedulerTopologyBindings, &out.SchedulerTopologyBindings
		*out = make([]SchedulerTopologyBinding, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTopologyBindingSpec.
func (in *ClusterTopologyBindingSpec) DeepCopy() *ClusterTopologyBindingSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterTopologyBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTopologyBindingStatus) DeepCopyInto(out *ClusterTopologyBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SchedulerTopologyStatuses != nil {
		in, out := &in.SchedulerTopologyStatuses, &out.SchedulerTopologyStatuses
		*out = make([]SchedulerTopologyStatus, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTopologyBindingStatus.
func (in *ClusterTopologyBindingStatus) DeepCopy() *ClusterTopologyBindingStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterTopologyBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadlessServiceConfig) DeepCopyInto(out *HeadlessServiceConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadlessServiceConfig.
func (in *HeadlessServiceConfig) DeepCopy() *HeadlessServiceConfig {
	if in == nil {
		return nil
	}
	out := new(HeadlessServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastError) DeepCopyInto(out *LastError) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastError.
func (in *LastError) DeepCopy() *LastError {
	if in == nil {
		return nil
	}
	out := new(LastError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastOperation) DeepCopyInto(out *LastOperation) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastOperation.
func (in *LastOperation) DeepCopy() *LastOperation {
	if in == nil {
		return nil
	}
	out := new(LastOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCSGResourceSharingFilter) DeepCopyInto(out *PCSGResourceSharingFilter) {
	*out = *in
	if in.ChildCliqueNames != nil {
		in, out := &in.ChildCliqueNames, &out.ChildCliqueNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCSGResourceSharingFilter.
func (in *PCSGResourceSharingFilter) DeepCopy() *PCSGResourceSharingFilter {
	if in == nil {
		return nil
	}
	out := new(PCSGResourceSharingFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCSGResourceSharingSpec) DeepCopyInto(out *PCSGResourceSharingSpec) {
	*out = *in
	out.ResourceSharingSpec = in.ResourceSharingSpec
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(PCSGResourceSharingFilter)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCSGResourceSharingSpec.
func (in *PCSGResourceSharingSpec) DeepCopy() *PCSGResourceSharingSpec {
	if in == nil {
		return nil
	}
	out := new(PCSGResourceSharingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCSResourceSharingFilter) DeepCopyInto(out *PCSResourceSharingFilter) {
	*out = *in
	if in.ChildCliqueNames != nil {
		in, out := &in.ChildCliqueNames, &out.ChildCliqueNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ChildScalingGroupNames != nil {
		in, out := &in.ChildScalingGroupNames, &out.ChildScalingGroupNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCSResourceSharingFilter.
func (in *PCSResourceSharingFilter) DeepCopy() *PCSResourceSharingFilter {
	if in == nil {
		return nil
	}
	out := new(PCSResourceSharingFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCSResourceSharingSpec) DeepCopyInto(out *PCSResourceSharingSpec) {
	*out = *in
	out.ResourceSharingSpec = in.ResourceSharingSpec
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(PCSResourceSharingFilter)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCSResourceSharingSpec.
func (in *PCSResourceSharingSpec) DeepCopy() *PCSResourceSharingSpec {
	if in == nil {
		return nil
	}
	out := new(PCSResourceSharingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodClique) DeepCopyInto(out *PodClique) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodClique.
func (in *PodClique) DeepCopy() *PodClique {
	if in == nil {
		return nil
	}
	out := new(PodClique)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodClique) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueList) DeepCopyInto(out *PodCliqueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodClique, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueList.
func (in *PodCliqueList) DeepCopy() *PodCliqueList {
	if in == nil {
		return nil
	}
	out := new(PodCliqueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodCliqueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueScalingGroup) DeepCopyInto(out *PodCliqueScalingGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueScalingGroup.
func (in *PodCliqueScalingGroup) DeepCopy() *PodCliqueScalingGroup {
	if in == nil {
		return nil
	}
	out := new(PodCliqueScalingGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodCliqueScalingGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueScalingGroupConfig) DeepCopyInto(out *PodCliqueScalingGroupConfig) {
	*out = *in
	if in.CliqueNames != nil {
		in, out := &in.CliqueNames, &out.CliqueNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(int32)
		**out = **in
	}
	if in.ScaleConfig != nil {
		in, out := &in.ScaleConfig, &out.ScaleConfig
		*out = new(AutoScalingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(RollingUpdateConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceSharing != nil {
		in, out := &in.ResourceSharing, &out.ResourceSharing
		*out = make([]PCSGResourceSharingSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopologyConstraint != nil {
		in, out := &in.TopologyConstraint, &out.TopologyConstraint
		*out = new(TopologyConstraint)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueScalingGroupConfig.
func (in *PodCliqueScalingGroupConfig) DeepCopy() *PodCliqueScalingGroupConfig {
	if in == nil {
		return nil
	}
	out := new(PodCliqueScalingGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueScalingGroupList) DeepCopyInto(out *PodCliqueScalingGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodCliqueScalingGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueScalingGroupList.
func (in *PodCliqueScalingGroupList) DeepCopy() *PodCliqueScalingGroupList {
	if in == nil {
		return nil
	}
	out := new(PodCliqueScalingGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodCliqueScalingGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueScalingGroupSpec) DeepCopyInto(out *PodCliqueScalingGroupSpec) {
	*out = *in
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(int32)
		**out = **in
	}
	if in.CliqueNames != nil {
		in, out := &in.CliqueNames, &out.CliqueNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueScalingGroupSpec.
func (in *PodCliqueScalingGroupSpec) DeepCopy() *PodCliqueScalingGroupSpec {
	if in == nil {
		return nil
	}
	out := new(PodCliqueScalingGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueScalingGroupStatus) DeepCopyInto(out *PodCliqueScalingGroupStatus) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(string)
		**out = **in
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.LastErrors != nil {
		in, out := &in.LastErrors, &out.LastErrors
		*out = make([]LastError, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CurrentPodCliqueSetGenerationHash != nil {
		in, out := &in.CurrentPodCliqueSetGenerationHash, &out.CurrentPodCliqueSetGenerationHash
		*out = new(string)
		**out = **in
	}
	if in.UpdateProgress != nil {
		in, out := &in.UpdateProgress, &out.UpdateProgress
		*out = new(PodCliqueScalingGroupUpdateProgress)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueScalingGroupStatus.
func (in *PodCliqueScalingGroupStatus) DeepCopy() *PodCliqueScalingGroupStatus {
	if in == nil {
		return nil
	}
	out := new(PodCliqueScalingGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueScalingGroupUpdateProgress) DeepCopyInto(out *PodCliqueScalingGroupUpdateProgress) {
	*out = *in
	in.UpdateStartedAt.DeepCopyInto(&out.UpdateStartedAt)
	if in.UpdateEndedAt != nil {
		in, out := &in.UpdateEndedAt, &out.UpdateEndedAt
		*out = (*in).DeepCopy()
	}
	if in.LastProgressedAt != nil {
		in, out := &in.LastProgressedAt, &out.LastProgressedAt
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueScalingGroupUpdateProgress.
func (in *PodCliqueScalingGroupUpdateProgress) DeepCopy() *PodCliqueScalingGroupUpdateProgress {
	if in == nil {
		return nil
	}
	out := new(PodCliqueScalingGroupUpdateProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueSet) DeepCopyInto(out *PodCliqueSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueSet.
func (in *PodCliqueSet) DeepCopy() *PodCliqueSet {
	if in == nil {
		return nil
	}
	out := new(PodCliqueSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodCliqueSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueSetList) DeepCopyInto(out *PodCliqueSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodCliqueSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueSetList.
func (in *PodCliqueSetList) DeepCopy() *PodCliqueSetList {
	if in == nil {
		return nil
	}
	out := new(PodCliqueSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodCliqueSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueSetReplicaUpdateProgress) DeepCopyInto(out *PodCliqueSetReplicaUpdateProgress) {
	*out = *in
	in.UpdateStartedAt.DeepCopyInto(&out.UpdateStartedAt)
	if in.UpdateEndedAt != nil {
		in, out := &in.UpdateEndedAt, &out.UpdateEndedAt
		*out = (*in).DeepCopy()
	}
	if in.InFlightEpochs != nil {
		in, out := &in.InFlightEpochs, &out.InFlightEpochs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueSetReplicaUpdateProgress.
func (in *PodCliqueSetReplicaUpdateProgress) DeepCopy() *PodCliqueSetReplicaUpdateProgress {
	if in == nil {
		return nil
	}
	out := new(PodCliqueSetReplicaUpdateProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueSetSpec) DeepCopyInto(out *PodCliqueSetSpec) {
	*out = *in
	if in.UpdateStrategy != nil {
		in, out := &in.UpdateStrategy, &out.UpdateStrategy
		*out = new(PodCliqueSetUpdateStrategy)
		**out = **in
	}
	in.Template.DeepCopyInto(&out.Template)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueSetSpec.
func (in *PodCliqueSetSpec) DeepCopy() *PodCliqueSetSpec {
	if in == nil {
		return nil
	}
	out := new(PodCliqueSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueSetStatus) DeepCopyInto(out *PodCliqueSetStatus) {
	*out = *in
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastErrors != nil {
		in, out := &in.LastErrors, &out.LastErrors
		*out = make([]LastError, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(string)
		**out = **in
	}
	if in.PodGangStatutes != nil {
		in, out := &in.PodGangStatutes, &out.PodGangStatutes
		*out = make([]PodGangStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CurrentGenerationHash != nil {
		in, out := &in.CurrentGenerationHash, &out.CurrentGenerationHash
		*out = new(string)
		**out = **in
	}
	if in.UpdateProgress != nil {
		in, out := &in.UpdateProgress, &out.UpdateProgress
		*out = new(PodCliqueSetUpdateProgress)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueSetStatus.
func (in *PodCliqueSetStatus) DeepCopy() *PodCliqueSetStatus {
	if in == nil {
		return nil
	}
	out := new(PodCliqueSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueSetTemplateSpec) DeepCopyInto(out *PodCliqueSetTemplateSpec) {
	*out = *in
	if in.Cliques != nil {
		in, out := &in.Cliques, &out.Cliques
		*out = make([]*PodCliqueTemplateSpec, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(PodCliqueTemplateSpec)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.StartupType != nil {
		in, out := &in.StartupType, &out.StartupType
		*out = new(CliqueStartupType)
		**out = **in
	}
	if in.HeadlessServiceConfig != nil {
		in, out := &in.HeadlessServiceConfig, &out.HeadlessServiceConfig
		*out = new(HeadlessServiceConfig)
		**out = **in
	}
	if in.TopologyConstraint != nil {
		in, out := &in.TopologyConstraint, &out.TopologyConstraint
		*out = new(TopologyConstraint)
		(*in).DeepCopyInto(*out)
	}
	if in.TerminationDelay != nil {
		in, out := &in.TerminationDelay, &out.TerminationDelay
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ResourceClaimTemplates != nil {
		in, out := &in.ResourceClaimTemplates, &out.ResourceClaimTemplates
		*out = make([]ResourceClaimTemplateConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceSharing != nil {
		in, out := &in.ResourceSharing, &out.ResourceSharing
		*out = make([]PCSResourceSharingSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodCliqueScalingGroupConfigs != nil {
		in, out := &in.PodCliqueScalingGroupConfigs, &out.PodCliqueScalingGroupConfigs
		*out = make([]PodCliqueScalingGroupConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueSetTemplateSpec.
func (in *PodCliqueSetTemplateSpec) DeepCopy() *PodCliqueSetTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PodCliqueSetTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueSetUpdateProgress) DeepCopyInto(out *PodCliqueSetUpdateProgress) {
	*out = *in
	in.UpdateStartedAt.DeepCopyInto(&out.UpdateStartedAt)
	if in.UpdateEndedAt != nil {
		in, out := &in.UpdateEndedAt, &out.UpdateEndedAt
		*out = (*in).DeepCopy()
	}
	if in.CurrentlyUpdating != nil {
		in, out := &in.CurrentlyUpdating, &out.CurrentlyUpdating
		*out = make([]PodCliqueSetReplicaUpdateProgress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InScopeStandalonePodCliques != nil {
		in, out := &in.InScopeStandalonePodCliques, &out.InScopeStandalonePodCliques
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InScopePodCliqueScalingGroups != nil {
		in, out := &in.InScopePodCliqueScalingGroups, &out.InScopePodCliqueScalingGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueSetUpdateProgress.
func (in *PodCliqueSetUpdateProgress) DeepCopy() *PodCliqueSetUpdateProgress {
	if in == nil {
		return nil
	}
	out := new(PodCliqueSetUpdateProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueSetUpdateStrategy) DeepCopyInto(out *PodCliqueSetUpdateStrategy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueSetUpdateStrategy.
func (in *PodCliqueSetUpdateStrategy) DeepCopy() *PodCliqueSetUpdateStrategy {
	if in == nil {
		return nil
	}
	out := new(PodCliqueSetUpdateStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueSpec) DeepCopyInto(out *PodCliqueSpec) {
	*out = *in
	in.PodSpec.DeepCopyInto(&out.PodSpec)
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(int32)
		**out = **in
	}
	if in.StartsAfter != nil {
		in, out := &in.StartsAfter, &out.StartsAfter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ScaleConfig != nil {
		in, out := &in.ScaleConfig, &out.ScaleConfig
		*out = new(AutoScalingConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueSpec.
func (in *PodCliqueSpec) DeepCopy() *PodCliqueSpec {
	if in == nil {
		return nil
	}
	out := new(PodCliqueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueStatus) DeepCopyInto(out *PodCliqueStatus) {
	*out = *in
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.LastErrors != nil {
		in, out := &in.LastErrors, &out.LastErrors
		*out = make([]LastError, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastScheduled != nil {
		in, out := &in.LastScheduled, &out.LastScheduled
		*out = (*in).DeepCopy()
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CurrentPodCliqueSetGenerationHash != nil {
		in, out := &in.CurrentPodCliqueSetGenerationHash, &out.CurrentPodCliqueSetGenerationHash
		*out = new(string)
		**out = **in
	}
	if in.CurrentPodTemplateHash != nil {
		in, out := &in.CurrentPodTemplateHash, &out.CurrentPodTemplateHash
		*out = new(string)
		**out = **in
	}
	if in.UpdateProgress != nil {
		in, out := &in.UpdateProgress, &out.UpdateProgress
		*out = new(PodCliqueUpdateProgress)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueStatus.
func (in *PodCliqueStatus) DeepCopy() *PodCliqueStatus {
	if in == nil {
		return nil
	}
	out := new(PodCliqueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueTemplateSpec) DeepCopyInto(out *PodCliqueTemplateSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TopologyConstraint != nil {
		in, out := &in.TopologyConstraint, &out.TopologyConstraint
		*out = new(TopologyConstraint)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceSharing != nil {
		in, out := &in.ResourceSharing, &out.ResourceSharing
		*out = make([]ResourceSharingSpec, len(*in))
		copy(*out, *in)
	}
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(RollingUpdateConfiguration)
		(*in).DeepCopyInto(*out)
	}
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueTemplateSpec.
func (in *PodCliqueTemplateSpec) DeepCopy() *PodCliqueTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PodCliqueTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCliqueUpdateProgress) DeepCopyInto(out *PodCliqueUpdateProgress) {
	*out = *in
	in.UpdateStartedAt.DeepCopyInto(&out.UpdateStartedAt)
	if in.UpdateEndedAt != nil {
		in, out := &in.UpdateEndedAt, &out.UpdateEndedAt
		*out = (*in).DeepCopy()
	}
	if in.LastProgressedAt != nil {
		in, out := &in.LastProgressedAt, &out.LastProgressedAt
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCliqueUpdateProgress.
func (in *PodCliqueUpdateProgress) DeepCopy() *PodCliqueUpdateProgress {
	if in == nil {
		return nil
	}
	out := new(PodCliqueUpdateProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGangEntry) DeepCopyInto(out *PodGangEntry) {
	*out = *in
	if in.PodCliques != nil {
		in, out := &in.PodCliques, &out.PodCliques
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PCSGReplicaIndices != nil {
		in, out := &in.PCSGReplicaIndices, &out.PCSGReplicaIndices
		*out = make(map[string][]int32, len(*in))
		for key, val := range *in {
			var outVal []int32
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]int32, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGangEntry.
func (in *PodGangEntry) DeepCopy() *PodGangEntry {
	if in == nil {
		return nil
	}
	out := new(PodGangEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGangMap) DeepCopyInto(out *PodGangMap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGangMap.
func (in *PodGangMap) DeepCopy() *PodGangMap {
	if in == nil {
		return nil
	}
	out := new(PodGangMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodGangMap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGangMapList) DeepCopyInto(out *PodGangMapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodGangMap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGangMapList.
func (in *PodGangMapList) DeepCopy() *PodGangMapList {
	if in == nil {
		return nil
	}
	out := new(PodGangMapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodGangMapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGangMapSpec) DeepCopyInto(out *PodGangMapSpec) {
	*out = *in
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]PodGangEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGangMapSpec.
func (in *PodGangMapSpec) DeepCopy() *PodGangMapSpec {
	if in == nil {
		return nil
	}
	out := new(PodGangMapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGangStatus) DeepCopyInto(out *PodGangStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGangStatus.
func (in *PodGangStatus) DeepCopy() *PodGangStatus {
	if in == nil {
		return nil
	}
	out := new(PodGangStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceClaimTemplateConfig) DeepCopyInto(out *ResourceClaimTemplateConfig) {
	*out = *in
	in.TemplateSpec.DeepCopyInto(&out.TemplateSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceClaimTemplateConfig.
func (in *ResourceClaimTemplateConfig) DeepCopy() *ResourceClaimTemplateConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceClaimTemplateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSharingSpec) DeepCopyInto(out *ResourceSharingSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSharingSpec.
func (in *ResourceSharingSpec) DeepCopy() *ResourceSharingSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSharingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingUpdateConfiguration) DeepCopyInto(out *RollingUpdateConfiguration) {
	*out = *in
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(int32)
		**out = **in
	}
	if in.ProgressDeadline != nil {
		in, out := &in.ProgressDeadline, &out.ProgressDeadline
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingUpdateConfiguration.
func (in *RollingUpdateConfiguration) DeepCopy() *RollingUpdateConfiguration {
	if in == nil {
		return nil
	}
	out := new(RollingUpdateConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerTopologyBinding) DeepCopyInto(out *SchedulerTopologyBinding) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerTopologyBinding.
func (in *SchedulerTopologyBinding) DeepCopy() *SchedulerTopologyBinding {
	if in == nil {
		return nil
	}
	out := new(SchedulerTopologyBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerTopologyStatus) DeepCopyInto(out *SchedulerTopologyStatus) {
	*out = *in
	out.SchedulerTopologyBinding = in.SchedulerTopologyBinding
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerTopologyStatus.
func (in *SchedulerTopologyStatus) DeepCopy() *SchedulerTopologyStatus {
	if in == nil {
		return nil
	}
	out := new(SchedulerTopologyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyConstraint) DeepCopyInto(out *TopologyConstraint) {
	*out = *in
	if in.Pack != nil {
		in, out := &in.Pack, &out.Pack
		*out = new(TopologyPackConstraint)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyConstraint.
func (in *TopologyConstraint) DeepCopy() *TopologyConstraint {
	if in == nil {
		return nil
	}
	out := new(TopologyConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyLevel) DeepCopyInto(out *TopologyLevel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyLevel.
func (in *TopologyLevel) DeepCopy() *TopologyLevel {
	if in == nil {
		return nil
	}
	out := new(TopologyLevel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyPackConstraint) DeepCopyInto(out *TopologyPackConstraint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyPackConstraint.
func (in *TopologyPackConstraint) DeepCopy() *TopologyPackConstraint {
	if in == nil {
		return nil
	}
	out := new(TopologyPackConstraint)
	in.DeepCopyInto(out)
	return out
}
